# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b308d840b29b15771c4208f9b2339dd63d3512863d810e8b23e69972cfe8319ebf3d0cb9a70b60f0bf965483fad8d4caa1ba33b1df74aeeec186141181e587c2

test:
  secret_key_base: 7ddb3b2e18965271bb6791cefd628bf1b96f40eebecfc5580ad2ac800dd517e7eeff4288afa8bbacb876a570b0e80e955adf1da7dfdb8158b68892c9d75536ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
